# Generated by Django 3.0.3 on 2020-03-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='student',
        ),
    ]
