# Generated by Django 3.0.3 on 2020-03-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpm', '0002_auto_20200303_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact', models.IntegerField(max_length=14)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
            ],
        ),
    ]
