# Generated by Django 3.0.3 on 2020-03-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpm', '0003_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
